import Head from 'next/head';
import BlogPageContent from '../../components/organisms/BlogPageContent';
import Footer from '../../components/organisms/Footer';
import Navbar from '../../components/organisms/Navbar';

const BlogPage = () => {
  return (
    <>
      <Head>
        <title>Cara Install Ulang Windows 10 Dengan Mudah</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />
      <BlogPageContent />
      <Footer />
    </>
  );
};

export default BlogPage;
