import Head from 'next/head';
import BlogContent from '../../components/organisms/BlogContent';
import BlogHeader from '../../components/organisms/BlogHeader';
import Footer from '../../components/organisms/Footer';
import Navbar from '../../components/organisms/Navbar';

const blog = () => {
  return (
    <>
      <Head>
        <title>Teknik Informatika E - Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar activeMenu="blog" />
      <BlogHeader />
      <BlogContent />
      <Footer />
    </>
  );
};

export default blog;
