import Head from 'next/head';
import AboutUs from '../components/organisms/AboutUs';
import Footer from '../components/organisms/Footer';
import MainBanner from '../components/organisms/MainBanner';
import Navbar from '../components/organisms/Navbar';
import OurBlogSection from '../components/organisms/OurBlogSection';
import OurGallerySection from '../components/organisms/OurGallerySection';
import QuotesSection from '../components/organisms/QuotesSection';

const Home = () => {
  return (
    <>
      <Head>
        <title>Teknik Informatika E - Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar activeMenu="home" />
      <MainBanner />
      <AboutUs />
      <QuotesSection />
      <OurBlogSection />
      <OurGallerySection />
      <Footer />
    </>
  );
};

export default Home;
